### ISSUE TITLE
Add generated java files to sources so IDEs don't throw errors

### ISSUE THREAD

**Issue by fischermatte** [nidi3/apikana-java#5]
Our current approach:

1. jsonschema2pojo plugin
` <outputDirectory>${project.build.directory}/api/model/java</outputDirectory>`

2. apikana-maven-plugin
`<generatedSourcesDirectory>${project.build.directory}/api/model/java</generatedSourcesDirectory>`

**Comment by nidi3** [comment]
Source files are generated now when using the parent pom or with the `package` task.
I guess that helps.
